default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_with_weather_intermediate_assessment_development
  url: <%= ENV["DATABASE_URL"] || 'postgres://localhost/todo_with_weather_intermediate_assessment_development' %>
  pool: 5

test:
  <<: *default
  database: todo_with_weather_intermediate_assessment_test
  url: <%= ENV["DATABASE_URL"] || 'postgres://localhost/todo_with_weather_intermediate_assessment_test' %>
  pool: 5

production:
  <<: *default
  database: todo_with_weather_intermediate_assessment_production
  username: todo_with_weather_intermediate_assessment
  password: <%= ENV["TODO_WITH_WEATHER_INTERMEDIATE_ASSESSMENT_DATABASE_PASSWORD"] %>
